version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./server
    container_name: rails-backend
    ports:
      - "3001:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build:
      context: ./client
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
    depends_on:
      - backend